### ISSUE TITLE
1018.c

### ISSUE THREAD

**Issue by caduamorimm-dev** [eduardo-mior/URI-Online-Judge-Solutions#12]
Olá, vi que não tem a solução 1018 em C, comecei a estudar agora e consegui resolver essa questão. Aceitaria o código pra compartilhar aqui?

**Comment by eduardo-mior** [comment]
Olá @caduamorimm-dev.

Eu ficaria muito feliz com a sua contribuição!

Se você quiser pode abrir um Pull request com a sua resolução do exercício, se não souber ou não conseguir abrir o Pull request pode enviar o código aqui mesmo.

**Comment by caduamorimm-dev** [comment]
Tentei fazer o Pull request, me avisa se deu certo. Caso contrário comento aqui!

**Comment by eduardo-mior** [comment]
@caduamorimm-dev não chegou nada, aqui no repositório do Github tem uma aba chamada "Pull requests" ai você clica lá e clica pra criar um novo pull requests, mas pra poder fazer isso você precisa ter um fork do projeto no seu perfil.

https://github.com/eduardo-mior/URI-Online-Judge-Solutions/pulls

**Comment by caduamorimm-dev** [comment]
Infelizmente não consegui, mas segue o código:


#include <stdio.h>

int main() {


      double raio, area, n;

      scanf("%lf", &raio);

            n = 3.14159;
            area = (raio * raio) * n;

      printf("A=%.4f\n", area);

    return 0;
}

**Comment by eduardo-mior** [comment]
@caduamorimm-dev agora deu certo o seus pullrequests, muito obrigado pela contribuição!
