### ISSUE TITLE
Organização para melhora da visualização dentro das categorias.

### ISSUE THREAD

**Issue by brunbrunbrun** [eduardo-mior/URI-Online-Judge-Solutions#4]
Na situação atual, a categoria **/Iniciante** contém +1000 arquivos, separados por `*URI* _numr_ *.* _extensão referente a linguagem usada para a solução_ `, gostaria de propor algumas possiveis alternativas para melhor organizar a categoria.

 - ### Dentro de cada categoria, agrupar em subpastas por linguagem:
![firefox_nzkqWeolaG](https://user-images.githubusercontent.com/82368316/159867386-0fca3d86-2c58-4755-b873-650d67095a92.png)

Seria mais facil de se agrupar, pois só precisaria filtrar pela extensão, **MAS** não ajudaria na visualização de problemas resolvidos em outras linguagens, para entender a resolução e aplicar em uma linguagem ainda não resolvida.

- ### Dentro de cada categoria, agrupar em subpastas por problema: 
![firefox_qCy8zR0vJb](https://user-images.githubusercontent.com/82368316/159867510-57756138-8efc-44d1-8dd2-e11d1e403788.png)

Seria um pouco menos facil de se agrupar e contribuir posteriormente, como também bem menos visual ja que teria muitas mais pastas, **MAS** seria melhor para encontrar um problema e, se esse ainda não tivesse resolução em uma linguagem, teria facilidade com a comparação para com os resolvidos em outras linguagens para se entender a logica por trás, e então tentar aplicar na linguagem ainda não resolvida.

**Comment by eduardo-mior** [comment]
Ambas as soluções possuem prós e contras então acho que não tem muito oque discutir, é mais uma questão visual.

Acredito eu que o melhor seria separar por categoria e depois por linguagem de programação, ou talvez por linguagem de programação e depois por categoria não sei qual seria o melhor.

Oque eu acho que seria interessante e que ajudaria bastante é colocar no README do projeto os exercícios que já foram resolvidos e suas respectivas linguagens, isso ajudaria bastante na hora de buscar um exercício ou verificar se ele já foi feito.

**Comment by brunbrunbrun** [comment]
Realmente, não tinha pensado nessa do README, parece bem mais interessante mesmo, e abre mais possibilidades na hora de fazer uma busca por exercício.
