### ISSUE TITLE
1047.js 

### ISSUE THREAD

**Issue by DanielSilva33** [eduardo-mior/URI-Online-Judge-Solutions#6]
Olá, o conteúdo que vc tem nesse repo é muito bom, porem no desafio 1047.js ele está incorreto, eu quebrei a cabeça tentando resolver, até mesmo consultei no seu repo mas acredito que a forma de testar esse desafio tenha mudado, depois de muito tempo fiz um solução que foi aceita pela plataforma.

```let line = lines.shift().split(" ");

let hoursInitial = parseInt(line[0]);
let minuteInitial = parseInt(line[1]);
let hoursFinal = parseInt(line[2]);
let minuteFinal = parseInt(line[3]);

let minutes = 0;
let hours = 0;

if (
  hoursInitial == hoursFinal &&
  minuteInitial == minuteFinal &&
  hoursInitial == minuteFinal
) {
  console.log("O JOGO DUROU 24 HORA(S) E 0 MINUTO(S)");
} else {
  if (hoursInitial > hoursFinal) {
    hours = 24 - hoursInitial + hoursFinal;
  } else if (hoursInitial < hoursFinal) {
    hours = 24 - (24 - hoursFinal + hoursInitial);
  }
  if (minuteInitial > minuteFinal) {
    minutes = 60 + minuteFinal - minuteInitial;
    if (hoursInitial == hoursFinal) {
      hours = 24 + hours - 1;
    } else {
      hours = hours - 1;
    }
  } else {
    minutes = minuteFinal - minuteInitial;
  }
  console.log(`O JOGO DUROU ${hours} HORA(S) E ${minutes} MINUTO(S)`);
}
```

Pelo o que eu percebi existe alguns testes que colocam que com essa solução nós retorna o resultado errado, fazendo com que não passe na verificação do Beecrowd, essa solução que eu fiz passou certinho!

Muito obrigado pelo conteúdo, espero contribuir para esse repo incrível!

**Comment by eduardo-mior** [comment]
@DanielSilva33 realmente houve alguma alteração nos inputs e na maneira como testam o desafio... Eu tinha resolvido esse desafio em Java em Junho de 2019 e depois em JavaScript em Julho também de 2019 e depois nunca mais mexi com ele.

Irei analisar para corrigir o exercício em Java. 

@DanielSilva33 Se você puder, abre um PullRequest com a sua solução em JavaScript que eu aceito seu PullRequest e você fica marcado colaborador no repositório 😄 .

**Comment by DanielSilva33** [comment]
@eduardo-mior Opa claro, acabei de criar o PR, muito obrigado pela participação no repo! 😄

**Comment by eduardo-mior** [comment]
@DanielSilva33 não localizei seu PR, tem certeza que criou?

**Comment by eduardo-mior** [comment]
@DanielSilva33 ????
